'''_main_.py
This script performs the end-to-end postprocessing and evaluation of Modelica code generated by LLMs. 
It handles output cleaning, model simulation, correctness checking, and statistical analysis.
'''
import os
import re
import json
import numpy as np
import pandas as pd
import scipy.io as sio
from OMPython import OMCSessionZMQ
from validation.text_postprocess import process_files, classify_files
from validation.model_test_for_model import process_version_model, load_libraries
from validation.result_analysis import analyze_relationship, add_type_to_results
from validation.model_functional_check import update_json_results, find_closest_values, adjust_length, calculate_mse, load_csv_data, load_mat_data
from tools.retain_mat_files import retain_mat_files
# ================= Helper Functions for Functional Validation =================

def find_closest_values(reference_data, validated_data):
    """Find the column in validated_data most similar to the last column of reference_data."""
    reference_column = reference_data[:, -1]
    validated_columns = validated_data[:, 1:]
    min_distance = float('inf')
    closest_column = None

    for col_idx in range(validated_columns.shape[1]):
        candidate_column = validated_columns[:, col_idx]
        distance = np.linalg.norm(candidate_column - reference_column)
        if distance < min_distance:
            min_distance = distance
            closest_column = candidate_column
    return closest_column

def adjust_length(data_1, data_2):
    """Align data_2 rows to the time points in data_1."""
    data1_time = data_1[:, 0]
    data2_time = data_2[:, 0]
    aligned_validated_data = []
    for ref_t in data1_time:
        closest_index = np.argmin(np.abs(data2_time - ref_t))
        aligned_validated_data.append(data_2[closest_index, :])
    return data_1, np.array(aligned_validated_data)

# ================= Main Script =================

# Initialize the OMC session
omc = OMCSessionZMQ()

def remove_empty_folders(path):
    removed_folders_count = 0
    for root, dirs, files in os.walk(path, topdown=False):
        for dir_name in dirs:
            dir_path = os.path.join(root, dir_name)
            if not os.listdir(dir_path):
                os.rmdir(dir_path)
                removed_folders_count += 1
    print(f"Removed totally {removed_folders_count} empty folders.")
    return removed_folders_count

def main():
    current_folder = os.path.dirname(os.path.abspath(__file__))
    
    # Configuration
    model_name = "GPT4o_test" # Adjust based on your current experiment
    input_folder = os.path.join(current_folder, f"result/{model_name}/output")
    output_folder = os.path.join(current_folder, f"result/{model_name}/model")
    simu_base_dir = os.path.join(current_folder, f"result/{model_name}/simulation")
    results_dir = os.path.join(current_folder, f"result/{model_name}")
    reference_csv_dir = os.path.join(current_folder, "validation/reference_model")
    
    os.makedirs(results_dir, exist_ok=True)

    # =============================================================================================
    # 1. Text Processing (Cleaning and Classification)
    # =============================================================================================
    process_files(input_folder, output_folder, 'model')
    classify_files(output_folder)
    
    # =============================================================================================
    # 2. Simulation and Verification (OMC Session)
    # =============================================================================================
    lib_files_dir = os.path.join(current_folder, "validation/library-OM")
    lib_files_json = os.path.join(current_folder, "json_files/libraries.json")
    with open(lib_files_json, 'r') as file:
        lib_files_data = json.load(file)

    all_check_results = {}
    for version, lib_files in lib_files_data.items():
        mo_files_dir = os.path.join(output_folder, f"model-{version}")
        simu_dir = os.path.join(simu_base_dir, f"simulation-{version}")
        os.makedirs(simu_dir, exist_ok=True)
        load_libraries(lib_files, lib_files_dir, version, omc)    
        model_results = process_version_model(version, mo_files_dir, simu_dir, all_check_results, lib_files, lib_files_dir, omc)
        omc.sendExpression("clear()")

    result_file = os.path.join(results_dir, "all_check_results_by_model.json")
    with open(result_file, 'w') as file:
        json.dump(model_results, file, indent=4)

    remove_empty_folders(simu_base_dir)
    retain_mat_files(simu_base_dir)

    # =============================================================================================
    # 3. Relationship Analysis (Statistical Summary)
    # =============================================================================================
    # Regular expression to match the model number in the file name
    pattern = re.compile(f'model_(\d+)_response_\d+\.txt')
    total_files = 0
    file_counts = {}
    for file_name in os.listdir(input_folder):
        if file_name.endswith('.txt'):
            match = pattern.match(file_name)
            if match:
                model_number = match.group(1)
                model_key = f"model_{model_number}"
                if model_key in file_counts:
                    file_counts[model_key] += 1
                else:
                    file_counts[model_key] = 1
                total_files += 1

    total_txt_files = {
        # "total_txt_files": total_files
    }

    sorted_file_counts = dict(sorted(file_counts.items(), key=lambda x: int(x[0].split('_')[1])))

    # Merge sorted counts into the result
    for key in sorted_file_counts:
        total_txt_files[key] = {
            "txt_files": sorted_file_counts[key]
            # "mo_count": sorted_model_counts.get(key, 0)  # If the model number is not in the model count, the default value is 0
        }

    output_file = os.path.join(results_dir, "results_analysis_model.json")
    models_file = "json_files/test_component.json"

    with open(models_file, 'r', encoding='utf-8') as file:
        models_data = json.load(file)['model']
    with open(result_file, 'r', encoding='utf-8') as file:
        data = json.load(file)

    analysis_results = analyze_relationship(data, total_files) 
    
    formatted_results = {"results": analysis_results["model_summary"]}

    # Merge results
    combined_results = {"results": {}}

    for model_key, result_data in formatted_results["results"].items():
        if model_key in total_txt_files:
            # Put 'txt_files' first
            combined_results["results"][model_key] = {
                "txt_files": total_txt_files[model_key]["txt_files"],
                **result_data
            }
        else:
            combined_results["results"][model_key] = result_data

    # Add 'type' field to the results
    combined_results["results"] = add_type_to_results(models_data, combined_results["results"])

    results = {"statistics": analysis_results["statistics"],
        "results": combined_results["results"] }

    # Save analysis results to JSON file
    with open(output_file, 'w', encoding='utf-8') as file:
        json.dump(results, file, indent=4)

    print(f"Analysis results saved to {output_file}")

    # =============================================================================================
    # 4. Functional Validation (MSE Checking)
    # =============================================================================================
    MSE_THRESHOLD = 1e-3
    results_json_path = output_file

    model_numbers = sorted(
        int(match.group(1))
        for key in total_txt_files.keys()
        if (match := re.fullmatch(r"model_(\d+)", key))
    )

    for n in model_numbers:
        passed_count = 0
        failed_count = 0
        print(f"\n\033[32mmodel_{n}\033[0m")

        # Regex to match reference CSV filename
        pattern = re.compile(f"{n}_.*\\.csv")
        matching_files = [f for f in os.listdir(reference_csv_dir) if pattern.match(f)]

        if not matching_files:
            reference_data = None
            print("\033[33mFailed to load reference data file, cannot proceed with validation.\033[0m")
            model_key = f"model_{n}"
            update_json_results(results_json_path, model_key, passed_count)
            continue
        
        # Load reference model data
        reference_csv_path = os.path.join(reference_csv_dir, matching_files[0])  # Path to reference model CSV
        reference_data = load_csv_data(reference_csv_path)

        # Match folders starting with model_{n}_
        folder_pattern = re.compile(f"model_{n}_")
        mat_files = []
        for root, dirs, files in os.walk(simu_base_dir):
            if folder_pattern.match(os.path.basename(root)):
                mat_files += [os.path.join(root, file) for file in files if file.endswith(".mat")]

        if not mat_files:
            print("\033[33mNo successful simulation cases found for this model, cannot proceed with validation.\033[0m")
            model_key = f"model_{n}"
            update_json_results(results_json_path, model_key, passed_count)
        else:
            for mat_file_path in mat_files:
                validated_data = load_mat_data(mat_file_path)
                # Extract folder name as ID path
                id_path = os.path.normpath(mat_file_path).split(os.sep)[-2]

                if validated_data is None:
                    print(f"\033[91mFailed to load MAT file {mat_file_path}, skipping.\033[0m")
                    failed_count += 1
                    continue
                if validated_data.size == 0:
                    print(f"\033[35mMAT file {mat_file_path} contains no valid results, skipping.\033[0m")
                    failed_count += 1
                    continue
                
                # Transpose validated data to align dimensions
                validated_data = validated_data.T

                try:
                    # Align rows/columns length
                    ref_rows, ref_cols = reference_data.shape
                    val_rows, val_cols = validated_data.shape
                    
                    if ref_rows < val_rows:
                        reference_data, validated_data = adjust_length(reference_data, validated_data)
                        print(f"\033[36m{id_path}: ref_rows < val_rows (Aligned)\033[0m")
                    elif ref_rows > val_rows:
                        validated_data, reference_data = adjust_length(validated_data, reference_data)
                        print(f"\033[36m{id_path}: ref_rows > val_rows (Aligned)\033[0m")

                    # Find closest values for matching
                    matched_validated_data = find_closest_values(reference_data, validated_data)

                    # Calculate Mean Squared Error (MSE)
                    mse = calculate_mse(reference_data[:, -1], matched_validated_data)

                    # Check against MSE threshold
                    if mse <= MSE_THRESHOLD:
                        print(f"{id_path} Functional Validation Passed: MSE = {mse:.6f} (Below threshold {MSE_THRESHOLD})")
                        passed_count += 1
                    else:
                        print(f"\033[91m{id_path} Functional Validation Failed: MSE = {mse:.6f} (Above threshold {MSE_THRESHOLD})\033[0m")
                        failed_count += 1

                except Exception as e:
                    print(f"{id_path} Error occurred during validation: {e}")

            print(f"\nTotal passed: {passed_count}\nTotal failed: {failed_count}")

            # Update final JSON results
            model_key = f"model_{n}"
            update_json_results(results_json_path, model_key, passed_count)

if __name__ == "__main__":
    main()